# Generated by Django 5.2.7 on 2026-01-08 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedores', '0002_vendedor_email_vendedor_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
    ]
