# Generated by Django 5.2.7 on 2025-11-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_operacion_base', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('costo_envio_sucursal', models.DecimalField(decimal_places=2, default=20.0, max_digits=10)),
                ('costo_extra_largo', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('costo_retraso_mensual', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuración',
            },
        ),
    ]
