# Generated by Django 5.2.7 on 2025-11-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='costo_urgente',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=10),
        ),
    ]
