# Generated by Django 5.2.7 on 2025-10-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='horario',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
