# Generated by Django 5.2.7 on 2025-10-05 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sucursales', '0001_initial'),
        ('vendedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('folio', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('comprador', models.CharField(max_length=255)),
                ('tamano_paquete', models.CharField(choices=[('CH', 'Chico'), ('M', 'Mediano'), ('G', 'Grande')], default='CH', max_length=2)),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('listo_para_entrega', 'Listo para entrega'), ('en_resguardo', 'En resguardo (Tiempo excedido)'), ('entregado', 'Entregado a comprador'), ('cancelado', 'Cancelado'), ('expirado', 'Expirado')], default='listo_para_entrega', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_expiracion', models.DateField(editable=False, null=True)),
                ('sucursal_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_destino', to='sucursales.sucursal')),
                ('sucursal_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_origen', to='sucursales.sucursal')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones', to='vendedores.vendedor')),
            ],
            options={
                'verbose_name': 'Operación',
                'verbose_name_plural': 'Operaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
