# Generated by Django 5.2.7 on 2025-11-22 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='entregado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operaciones_entregadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operacion',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='operacion',
            name='recibido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operaciones_recibidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operacion',
            name='tipo_entrega',
            field=models.CharField(choices=[('normal', 'Normal'), ('urgente', 'Urgente')], default='normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='estado',
            field=models.CharField(choices=[('listo_para_entrega', 'Listo para entrega'), ('en_resguardo', 'En resguardo (Tiempo excedido)'), ('en_transito', 'En tránsito'), ('entregado', 'Entregado a comprador'), ('cancelado', 'Cancelado'), ('expirado', 'Expirado')], default='listo_para_entrega', max_length=20),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='tamano_paquete',
            field=models.CharField(choices=[('CH', 'Chico'), ('M', 'Mediano'), ('G', 'Grande'), ('XL', 'Extra Largo')], default='CH', max_length=2),
        ),
    ]
