# Generated by Django 5.2.7 on 2026-01-08 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0002_operacion_entregado_por_operacion_peso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacion',
            name='tamano_paquete',
            field=models.CharField(choices=[('STD', 'Estándar'), ('XL', 'Extra Largo')], default='STD', max_length=3),
        ),
    ]
